// <auto-generated />
using JsTree.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace JsTree.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250714102153_init1")]
    partial class init1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("JsTree.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsActive = true,
                            Name = "Programming"
                        },
                        new
                        {
                            Id = 2,
                            IsActive = true,
                            Name = "Design"
                        },
                        new
                        {
                            Id = 3,
                            IsActive = true,
                            Name = "Marketing"
                        });
                });

            modelBuilder.Entity("JsTree.Models.Course", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Instructor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Courses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Instructor = "John Doe",
                            IsActive = true,
                            Name = "C# Basics",
                            Price = 49.99m
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            Instructor = "Jane Smith",
                            IsActive = true,
                            Name = "Advanced JavaScript",
                            Price = 59.99m
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 2,
                            Instructor = "Alice Johnson",
                            IsActive = true,
                            Name = "UI/UX Design",
                            Price = 39.99m
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 3,
                            Instructor = "Bob Brown",
                            IsActive = true,
                            Name = "Digital Marketing 101",
                            Price = 29.99m
                        });
                });

            modelBuilder.Entity("JsTree.Models.Course", b =>
                {
                    b.HasOne("JsTree.Models.Category", "Category")
                        .WithMany("Courses")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("JsTree.Models.Category", b =>
                {
                    b.Navigation("Courses");
                });
#pragma warning restore 612, 618
        }
    }
}
